import { ATTEMPT_STAGES, type AttemptClosureReason, type AttemptStage } from "./contracts.js";

const ATTEMPT_CLOSURE_ALLOWED_STAGES: Readonly<Record<AttemptClosureReason, readonly AttemptStage[]>> = {
  AUDIT_ACCEPTED: ["AUDITING"],
  AUDIT_REJECTED: ["AUDITING"],
  EXECUTOR_UNAVAILABLE: ["ADMITTED", "EXECUTOR_DISPATCH_AUTHORIZED"],
  EXECUTOR_PROCESS_FAILURE: ["EXECUTOR_RUNNING", "POST_EXECUTOR_CAPTURE", "EVIDENCE_CAPTURING", "VALIDATING"],
  EXECUTOR_TIMED_OUT: ["EXECUTOR_RUNNING", "POST_EXECUTOR_CAPTURE"],
  EXECUTOR_CANCELLED: ["ADMITTED", "EXECUTOR_DISPATCH_AUTHORIZED", "EXECUTOR_RUNNING"],
  EXECUTOR_PROTOCOL_FAILURE: ["EXECUTOR_DISPATCH_AUTHORIZED", "EXECUTOR_RUNNING", "POST_EXECUTOR_CAPTURE", "EVIDENCE_CAPTURING", "VALIDATING"],
  VALIDATION_INFRASTRUCTURE_EXHAUSTED: ["VALIDATING"],
  CONTROL_PLANE_VIOLATION: ATTEMPT_STAGES,
  RECONCILIATION_REQUIRED: ATTEMPT_STAGES,
  CANCELLED_AT_BOUNDARY: ATTEMPT_STAGES,
  BUDGET_EXHAUSTED: ATTEMPT_STAGES,
};

export function isAttemptClosureAllowed(stage: AttemptStage, reason: AttemptClosureReason): boolean {
  return ATTEMPT_CLOSURE_ALLOWED_STAGES[reason]?.includes(stage) ?? false;
}
