/**
 * The document bundle produced by the single authoring call (RF-004).
 *
 * The generator returns typed `path`/`content` pairs; the orchestrator — not
 * the model — creates directories, writes files, derives the manifest, and
 * publishes. Materialization is deliberately paranoid: a bundle is untrusted
 * input that decides what lands in the developer's repository.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { HARNESS_BUDGET } from "./harness-budget.js";

export const DOCUMENT_BUNDLE_CONTRACT = "rb-harness-documents/v1" as const;
export const DOCUMENT_BUNDLE_BEGIN = "RB_HARNESS_DOCUMENTS_JSON_BEGIN";
export const DOCUMENT_BUNDLE_END = "RB_HARNESS_DOCUMENTS_JSON_END";

export interface GeneratedDocument {
  path: string;
  content: string;
}

export interface DocumentBundle {
  contract: typeof DOCUMENT_BUNDLE_CONTRACT;
  status: "complete" | "blocked";
  summary: string;
  documents: GeneratedDocument[];
  blocked: string[];
}

/** Paths the orchestrator owns; a bundle may never claim them. */
const CODE_OWNED_PATHS = new Set([".rb/rb-manifest.json", ".rb/artifacts.tsv"]);

function normalizeLogicalPath(value: unknown, index: number): string {
  if (typeof value !== "string" || !value.trim()) {
    throw new Error(`document ${index + 1} has no path`);
  }
  const path = value.trim().replaceAll("\\", "/").replace(/^\.\//, "");
  if (path.includes("\0") || path.length > 400) throw new Error(`document ${index + 1} has an unsupported path`);
  if (path.startsWith("/") || /^[A-Za-z]:\//.test(path)) throw new Error(`document path must be project-relative: ${path}`);
  const segments = path.split("/");
  if (segments.some((segment) => segment === "" || segment === "." || segment === "..")) {
    throw new Error(`document path must not contain empty or relative segments: ${path}`);
  }
  if (!path.startsWith(".rb/")) {
    throw new Error(`documents may be written only under .rb/: ${path}`);
  }
  if (path.startsWith(".rb/runs/") || path === ".rb/runs") {
    throw new Error(`.rb/runs is Ralph control-plane state and is never written by the Harness: ${path}`);
  }
  if (CODE_OWNED_PATHS.has(path)) {
    throw new Error(`${path} is generated by the orchestrator and must not appear in the bundle`);
  }
  return path;
}

function normalizeContent(value: unknown, path: string): string {
  if (typeof value !== "string") throw new Error(`document ${path} has no string content`);
  if (Buffer.byteLength(value) > HARNESS_BUDGET.documents.maxDocumentBytes) {
    throw new Error(`document ${path} exceeds ${HARNESS_BUDGET.documents.maxDocumentBytes} bytes`);
  }
  const normalized = value.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  if (!normalized.trim()) throw new Error(`document ${path} is empty`);
  return normalized.endsWith("\n") ? normalized : `${normalized}\n`;
}

function stringArray(value: unknown, label: string): string[] {
  if (value === undefined) return [];
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string" || !entry.trim())) {
    throw new Error(`${label} must be an array of non-empty strings`);
  }
  return value.map((entry) => (entry as string).trim());
}

/**
 * Locate the envelope in provider output. Surrounding prose and Markdown
 * fences are tolerated — a superficial formatting habit must not throw away a
 * complete, paid-for response — but a missing terminator is reported as a
 * truncated envelope so the caller can distinguish it from a protocol refusal.
 */
export function extractEnvelope(output: string, begin: string, end: string, label: string): string {
  const start = output.indexOf(begin);
  if (start < 0) throw new Error(`provider output does not contain the ${label} envelope`);
  const finish = output.indexOf(end, start + begin.length);
  if (finish < 0) throw new Error(`the ${label} envelope was truncated before its terminator`);
  let source = output.slice(start + begin.length, finish).trim();
  const fenced = source.match(/^```(?:json)?\s*\n([\s\S]*?)\n```$/);
  if (fenced?.[1]) source = fenced[1].trim();
  if (!source) throw new Error(`the ${label} envelope is empty`);
  return source;
}

export function parseDocumentBundle(output: string): DocumentBundle {
  const source = extractEnvelope(output, DOCUMENT_BUNDLE_BEGIN, DOCUMENT_BUNDLE_END, "document bundle");
  if (Buffer.byteLength(source) > HARNESS_BUDGET.documents.maxBundleBytes) {
    throw new Error(`document bundle exceeds ${HARNESS_BUDGET.documents.maxBundleBytes} bytes`);
  }
  let value: unknown;
  try {
    value = JSON.parse(source);
  } catch {
    throw new Error("provider returned malformed document bundle JSON");
  }
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("document bundle must be an object");
  const bundle = value as Record<string, unknown>;
  const allowed = new Set(["contract", "status", "summary", "documents", "blocked"]);
  for (const key of Object.keys(bundle)) {
    if (!allowed.has(key)) throw new Error(`unsupported document bundle field: ${key}`);
  }
  if (bundle.contract !== DOCUMENT_BUNDLE_CONTRACT) {
    throw new Error(`document bundle contract must be ${DOCUMENT_BUNDLE_CONTRACT}`);
  }
  if (bundle.status !== "complete" && bundle.status !== "blocked") {
    throw new Error("document bundle status must be complete or blocked");
  }
  if (typeof bundle.summary !== "string" || !bundle.summary.trim()) {
    throw new Error("document bundle must carry a summary");
  }
  if (!Array.isArray(bundle.documents)) throw new Error("document bundle documents must be an array");
  if (bundle.documents.length > HARNESS_BUDGET.documents.maxDocuments) {
    throw new Error(`document bundle exceeds ${HARNESS_BUDGET.documents.maxDocuments} documents`);
  }
  const documents: GeneratedDocument[] = [];
  const seen = new Set<string>();
  bundle.documents.forEach((entry, index) => {
    if (!entry || typeof entry !== "object" || Array.isArray(entry)) throw new Error(`document ${index + 1} must be an object`);
    const record = entry as Record<string, unknown>;
    for (const key of Object.keys(record)) {
      if (key !== "path" && key !== "content") throw new Error(`unsupported document field: ${key}`);
    }
    const path = normalizeLogicalPath(record.path, index);
    if (seen.has(path)) throw new Error(`document bundle declares ${path} twice`);
    seen.add(path);
    documents.push({ path, content: normalizeContent(record.content, path) });
  });
  const blocked = stringArray(bundle.blocked, "document bundle blocked");
  if (bundle.status === "blocked" && !blocked.length) {
    throw new Error("a blocked document bundle must name the missing decision in blocked");
  }
  if (bundle.status === "complete" && !documents.length) {
    throw new Error("a complete document bundle must contain at least one document");
  }
  // Deterministic order so materialization, hashing, and diffing are stable.
  documents.sort((left, right) => left.path.localeCompare(right.path));
  return {
    contract: DOCUMENT_BUNDLE_CONTRACT,
    status: bundle.status,
    summary: bundle.summary.trim(),
    documents,
    blocked,
  };
}

/**
 * Merge a repair bundle onto the authored bundle: repaired documents replace
 * their originals by path, new documents are added, and every untouched
 * document is preserved byte for byte.
 */
export function mergeDocumentBundles(base: DocumentBundle, repair: DocumentBundle): DocumentBundle {
  const merged = new Map(base.documents.map((document) => [document.path, document]));
  for (const document of repair.documents) merged.set(document.path, document);
  return {
    contract: DOCUMENT_BUNDLE_CONTRACT,
    status: repair.status,
    summary: repair.summary,
    documents: [...merged.values()].sort((left, right) => left.path.localeCompare(right.path)),
    blocked: repair.blocked,
  };
}

/**
 * Write a bundle into the staging tree, whose artifact directory is `.rb`.
 */
export async function materializeDocuments(
  stagingRoot: string,
  bundle: DocumentBundle,
): Promise<string[]> {
  const root = resolve(stagingRoot);
  const written: string[] = [];
  for (const document of bundle.documents) {
    const target = resolve(root, document.path);
    const relativePath = relative(root, target).split(sep).join("/");
    if (relativePath !== document.path) throw new Error(`document path escapes the staging root: ${document.path}`);
    await mkdir(dirname(target), { recursive: true, mode: 0o700 });
    await writeFile(target, document.content, { encoding: "utf8", mode: 0o644, flag: "w" });
    written.push(document.path);
  }
  return written;
}

/** Bundle excerpts for the single structural repair; only affected files travel. */
export function documentExcerpts(bundle: DocumentBundle, paths: Iterable<string>): GeneratedDocument[] {
  const wanted = new Set(paths);
  return bundle.documents.filter((document) => wanted.has(document.path));
}
