/**
 * The document bundle assembled from bounded authoring parts (RF-004).
 *
 * The generator returns typed `path`/`content` pairs; the orchestrator — not
 * the model — creates directories, writes files, derives the manifest, and
 * publishes. Materialization is deliberately paranoid: a bundle is untrusted
 * input that decides what lands in the developer's repository.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { HARNESS_BUDGET } from "./harness-budget.js";

export const DOCUMENT_BUNDLE_CONTRACT = "rb-harness-documents/v1" as const;
export const DOCUMENT_BUNDLE_BEGIN = "RB_HARNESS_DOCUMENTS_JSON_BEGIN";
export const DOCUMENT_BUNDLE_END = "RB_HARNESS_DOCUMENTS_JSON_END";

export interface GeneratedDocument {
  path: string;
  content: string;
}

export interface DocumentBundle {
  contract: typeof DOCUMENT_BUNDLE_CONTRACT;
  status: "complete" | "blocked";
  summary: string;
  documents: GeneratedDocument[];
  blocked: string[];
}

/** Paths the orchestrator owns; a bundle may never claim them. */
const CODE_OWNED_PATHS = new Set([".rb/rb-manifest.json", ".rb/artifacts.tsv"]);

/**
 * A defect the representation-only formatter structurally cannot repair.
 *
 * The formatter is forbidden from changing substance, and a document path *is*
 * substance: where a document goes is a decision, not a serialization detail.
 * Sending such a defect through the formatter buys three paid attempts that
 * can only fail, so the caller replans instead.
 */
export class DocumentSubstanceError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "DocumentSubstanceError";
  }
}

export function normalizeGeneratedDocumentPath(value: unknown, index: number): string {
  if (typeof value !== "string" || !value.trim()) {
    throw new Error(`document ${index + 1} has no path`);
  }
  const path = value.trim().replaceAll("\\", "/").replace(/^\.\//, "");
  if (path.includes("\0") || path.length > 400) throw new Error(`document ${index + 1} has an unsupported path`);
  if (path.startsWith("/") || /^[A-Za-z]:\//.test(path)) throw new DocumentSubstanceError(`document path must be project-relative: ${path}`);
  const segments = path.split("/");
  if (segments.some((segment) => segment === "" || segment === "." || segment === "..")) {
    throw new DocumentSubstanceError(`document path must not contain empty or relative segments: ${path}`);
  }
  if (!path.startsWith(".rb/")) {
    throw new DocumentSubstanceError(`documents may be written only under .rb/: ${path}`);
  }
  if (path.startsWith(".rb/runs/") || path === ".rb/runs") {
    throw new DocumentSubstanceError(`.rb/runs is Ralph control-plane state and is never written by the Harness: ${path}`);
  }
  if (CODE_OWNED_PATHS.has(path)) {
    throw new DocumentSubstanceError(`${path} is generated by the orchestrator and must not appear in the bundle`);
  }
  return path;
}

export function normalizeGeneratedDocumentContent(value: unknown, path: string): string {
  if (typeof value !== "string") throw new Error(`document ${path} has no string content`);
  if (Buffer.byteLength(value) > HARNESS_BUDGET.documents.maxDocumentBytes) {
    throw new Error(`document ${path} exceeds ${HARNESS_BUDGET.documents.maxDocumentBytes} bytes`);
  }
  const normalized = value.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
  if (!normalized.trim()) throw new Error(`document ${path} is empty`);
  return normalized.endsWith("\n") ? normalized : `${normalized}\n`;
}

export function normalizeGeneratedDocument(pathValue: unknown, contentValue: unknown, index: number): GeneratedDocument {
  const path = normalizeGeneratedDocumentPath(pathValue, index);
  return { path, content: normalizeGeneratedDocumentContent(contentValue, path) };
}

function stringArray(value: unknown, label: string): string[] {
  if (value === undefined) return [];
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string" || !entry.trim())) {
    throw new Error(`${label} must be an array of non-empty strings`);
  }
  return value.map((entry) => (entry as string).trim());
}

/**
 * Locate the envelope in provider output. Surrounding prose and Markdown
 * fences are tolerated — a superficial formatting habit must not throw away a
 * complete, paid-for response — but a missing terminator is reported as a
 * truncated envelope so the caller can distinguish it from a protocol refusal.
 */
export function extractEnvelope(output: string, begin: string, end: string, label: string): string {
  const start = output.indexOf(begin);
  if (start < 0) throw new Error(`provider output does not contain the ${label} envelope`);
  const finish = output.indexOf(end, start + begin.length);
  if (finish < 0) throw new Error(`the ${label} envelope was truncated before its terminator`);
  let source = output.slice(start + begin.length, finish).trim();
  const fenced = source.match(/^```(?:json)?\s*\n([\s\S]*?)\n```$/);
  if (fenced?.[1]) source = fenced[1].trim();
  if (!source) throw new Error(`the ${label} envelope is empty`);
  return source;
}

/**
 * Prefer the declared envelope, but preserve a paid response that is already
 * one valid JSON object and merely omitted the marker lines. Surrounding
 * analysis without a JSON object is still rejected and enters the bounded
 * provider-neutral formatting boundary.
 */
export function extractEnvelopeOrJson(output: string, begin: string, end: string, label: string): string {
  if (output.includes(begin)) return extractEnvelope(output, begin, end, label);
  const trimmed = output.trim();
  const unfenced = trimmed.startsWith("```") && trimmed.endsWith("```")
    ? trimmed.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim()
    : trimmed;
  const starts: number[] = [];
  for (let index = unfenced.indexOf("{"); index >= 0; index = unfenced.indexOf("{", index + 1)) starts.push(index);
  const last = unfenced.lastIndexOf("}");
  for (const start of starts) {
    if (last <= start) break;
    const candidate = unfenced.slice(start, last + 1);
    try {
      const parsed = JSON.parse(candidate);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) return candidate;
    } catch { /* try the next opening brace */ }
  }
  throw new Error(`provider output does not contain the ${label} envelope`);
}

export function parseDocumentBundle(output: string): DocumentBundle {
  const source = extractEnvelopeOrJson(output, DOCUMENT_BUNDLE_BEGIN, DOCUMENT_BUNDLE_END, "document bundle");
  if (Buffer.byteLength(source) > HARNESS_BUDGET.documents.maxBundleBytes) {
    throw new Error(`document bundle exceeds ${HARNESS_BUDGET.documents.maxBundleBytes} bytes`);
  }
  let value: unknown;
  try {
    value = JSON.parse(source);
  } catch {
    throw new Error("provider returned malformed document bundle JSON");
  }
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("document bundle must be an object");
  const bundle = value as Record<string, unknown>;
  const allowed = new Set(["contract", "status", "summary", "documents", "blocked"]);
  for (const key of Object.keys(bundle)) {
    if (!allowed.has(key)) throw new Error(`unsupported document bundle field: ${key}`);
  }
  if (bundle.contract !== DOCUMENT_BUNDLE_CONTRACT) {
    throw new Error(`document bundle contract must be ${DOCUMENT_BUNDLE_CONTRACT}`);
  }
  if (bundle.status !== "complete" && bundle.status !== "blocked") {
    throw new Error("document bundle status must be complete or blocked");
  }
  if (typeof bundle.summary !== "string" || !bundle.summary.trim()) {
    throw new Error("document bundle must carry a summary");
  }
  if (!Array.isArray(bundle.documents)) throw new Error("document bundle documents must be an array");
  if (bundle.documents.length > HARNESS_BUDGET.documents.maxDocuments) {
    throw new Error(`document bundle exceeds ${HARNESS_BUDGET.documents.maxDocuments} documents`);
  }
  const documents: GeneratedDocument[] = [];
  const seen = new Set<string>();
  bundle.documents.forEach((entry, index) => {
    if (!entry || typeof entry !== "object" || Array.isArray(entry)) throw new Error(`document ${index + 1} must be an object`);
    const record = entry as Record<string, unknown>;
    for (const key of Object.keys(record)) {
      if (key !== "path" && key !== "content") throw new Error(`unsupported document field: ${key}`);
    }
    const path = normalizeGeneratedDocumentPath(record.path, index);
    if (seen.has(path)) throw new Error(`document bundle declares ${path} twice`);
    seen.add(path);
    documents.push({ path, content: normalizeGeneratedDocumentContent(record.content, path) });
  });
  const blocked = stringArray(bundle.blocked, "document bundle blocked");
  if (bundle.status === "blocked" && !blocked.length) {
    throw new Error("a blocked document bundle must name the missing decision in blocked");
  }
  if (bundle.status === "complete" && !documents.length) {
    throw new Error("a complete document bundle must contain at least one document");
  }
  // Deterministic order so materialization, hashing, and diffing are stable.
  documents.sort((left, right) => left.path.localeCompare(right.path));
  return {
    contract: DOCUMENT_BUNDLE_CONTRACT,
    status: bundle.status,
    summary: bundle.summary.trim(),
    documents,
    blocked,
  };
}

/**
 * Merge a repair bundle onto the authored bundle: repaired documents replace
 * their originals by path, new documents are added, and every untouched
 * document is preserved byte for byte.
 */
export function mergeDocumentBundles(base: DocumentBundle, repair: DocumentBundle): DocumentBundle {
  const merged = new Map(base.documents.map((document) => [document.path, document]));
  for (const document of repair.documents) merged.set(document.path, document);
  return {
    contract: DOCUMENT_BUNDLE_CONTRACT,
    status: repair.status,
    summary: repair.summary,
    documents: [...merged.values()].sort((left, right) => left.path.localeCompare(right.path)),
    blocked: repair.blocked,
  };
}

function record(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

/**
 * Canonicalize the legacy nested HTTP assertion shape without weakening
 * rb-operational/v1. The transformation is lossless and runs only when every
 * nested field has one exact representation in the current probe contract.
 */
function normalizeOperationalProbe(value: unknown): boolean {
  if (!record(value) || value.kind !== "http" || !record(value.expect)) return false;
  const expectation = value.expect;
  if (Object.keys(expectation).some((key) => key !== "statusCode" && key !== "bodyIncludes")) return false;
  if (expectation.statusCode !== undefined) {
    if (value.status !== undefined && value.status !== expectation.statusCode) return false;
    value.status = expectation.statusCode;
  }
  if (expectation.bodyIncludes !== undefined) {
    if (value.bodyIncludes !== undefined && JSON.stringify(value.bodyIncludes) !== JSON.stringify(expectation.bodyIncludes)) return false;
    value.bodyIncludes = expectation.bodyIncludes;
  }
  delete value.expect;
  return true;
}

function normalizeOperationalDocument(content: string): string {
  let value: unknown;
  try { value = JSON.parse(content); }
  catch { return content; }
  if (!record(value) || value.contract !== "rb-operational/v1" || !Array.isArray(value.scenarios)) return content;
  let changed = false;
  for (const scenario of value.scenarios) {
    if (!record(scenario) || !Array.isArray(scenario.steps)) continue;
    for (const step of scenario.steps) {
      if (!record(step)) continue;
      if (step.kind === "process") {
        changed = normalizeOperationalProbe(step.ready) || changed;
        if (Array.isArray(step.checks)) {
          for (const check of step.checks) changed = normalizeOperationalProbe(check) || changed;
        }
      } else {
        changed = normalizeOperationalProbe(step) || changed;
      }
    }
  }
  return changed ? `${JSON.stringify(value, null, 2)}\n` : content;
}

/** Remove only a task's redundant reference to an enclosing phase dependency. */
function normalizeExecutionDependencies(content: string): string {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  let phaseDependencies = new Set<string>();
  let changed = false;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (/^## Phase [0-9]+:/.test(line)) {
      phaseDependencies = new Set<string>();
      continue;
    }
    const phase = line.match(/^\*\*Depends on:\*\*\s*(.+)$/);
    if (phase?.[1]) {
      phaseDependencies = new Set(phase[1].split(",").map((entry) => entry.trim()).filter((entry) => /^P[0-9]{2}$/.test(entry)));
      continue;
    }
    const task = line.match(/^(  - \*\*Depends on:\*\*\s*)(.+)$/);
    if (!task?.[1] || !task[2]) continue;
    const dependencies = task[2].split(",").map((entry) => entry.trim()).filter(Boolean);
    const retained = dependencies.filter((dependency) => !phaseDependencies.has(dependency));
    if (retained.length === dependencies.length) continue;
    lines[index] = `${task[1]}${retained.length ? retained.join(", ") : "none"}`;
    changed = true;
  }
  return changed ? lines.join("\n") : content;
}

export function normalizeGeneratedArtifactContent(path: string, content: string): string {
  if (path.endsWith("/OPERATIONS.json")) return normalizeOperationalDocument(content);
  if (path.endsWith("/PHASES.md")) return normalizeExecutionDependencies(content);
  return content;
}

/**
 * Write a bundle into the staging tree, whose artifact directory is `.rb`.
 */
export async function materializeDocuments(
  stagingRoot: string,
  bundle: DocumentBundle,
): Promise<string[]> {
  const root = resolve(stagingRoot);
  const written: string[] = [];
  for (const document of bundle.documents) {
    const target = resolve(root, document.path);
    const relativePath = relative(root, target).split(sep).join("/");
    if (relativePath !== document.path) throw new Error(`document path escapes the staging root: ${document.path}`);
    await mkdir(dirname(target), { recursive: true, mode: 0o700 });
    await writeFile(target, normalizeGeneratedArtifactContent(document.path, document.content), { encoding: "utf8", mode: 0o644, flag: "w" });
    written.push(document.path);
  }
  return written;
}

/** Bundle excerpts for the single structural repair; only affected files travel. */
export function documentExcerpts(bundle: DocumentBundle, paths: Iterable<string>): GeneratedDocument[] {
  const wanted = new Set(paths);
  return bundle.documents.filter((document) => wanted.has(document.path));
}
