import type { ValidationIssue } from "./types.js";
import { isIsoDateTime, isSafeRelativePath, normalizedRelativePathKey } from "./headless-contract.js";

export interface ProjectPackageValidation { valid: boolean; issues: ValidationIssue[]; document?: Record<string, unknown>; }
const HASH = /^[a-f0-9]{64}$/;
const VALIDATIONS = new Set(["paths", "contract", "operations", "manifest", "tree", "secrets", "physical-inventory"]);
const PACKAGE_MANIFEST_PATH_KEY = normalizedRelativePathKey("RB-PACKAGE-MANIFEST.json");
const object = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === "object" && !Array.isArray(value);
function add(issues: ValidationIssue[], code: string, message: string, path: string): void { issues.push({ code, message, severity: "error", path }); }
function shape(value: unknown, allowed: string[], required: string[], issues: ValidationIssue[], path: string): Record<string, unknown> | undefined { if (!object(value)) { add(issues, "package.object", "Expected an object", path); return; } for (const key of Object.keys(value)) if (!allowed.includes(key)) add(issues, "package.property.unknown", `Unknown property ${key}`, `${path}.${key}`); for (const key of required) if (!(key in value)) add(issues, "package.property.required", `Missing required property ${key}`, `${path}.${key}`); return value; }
function denseArray(value: unknown, issues: ValidationIssue[], path: string): value is unknown[] { if (!Array.isArray(value)) return false; for (let index = 0; index < value.length; index += 1) if (!(index in value)) { add(issues, "package.array.sparse", "Arrays must not contain empty entries", `${path}[${index}]`); return false; } return true; }
function text(value: unknown, issues: ValidationIssue[], path: string, max = 200): void { if (typeof value !== "string" || Array.from(value).length < 1 || Array.from(value).length > max) add(issues, "package.string", "Expected a non-empty string", path); }
function hash(value: unknown, issues: ValidationIssue[], path: string): void { if (typeof value !== "string" || !HASH.test(value)) add(issues, "package.sha256", "Expected a lowercase SHA-256 hash", path); }

export function validateProjectPackageValue(value: unknown): ProjectPackageValidation {
  const issues: ValidationIssue[] = [];
  const root = shape(value, ["contract", "status", "project", "artifactSet", "revision", "sources", "harness", "generation", "contracts", "validation", "files", "generatedAt"], ["contract", "status", "project", "artifactSet", "revision", "sources", "harness", "generation", "contracts", "validation", "files", "generatedAt"], issues, "$");
  if (!root) return { valid: false, issues };
  if (root.contract !== "rb-project-package/v1") add(issues, "package.contract", "contract must be rb-project-package/v1", "$.contract"); if (root.status !== "ready") add(issues, "package.status", "status must be ready", "$.status");
  const project = shape(root.project, ["id", "name"], ["id", "name"], issues, "$.project"); if (project) { if (typeof project.id !== "string" || Array.from(project.id).length > 100 || !/^[a-z0-9][a-z0-9-]*$/.test(project.id)) add(issues, "package.project.id", "Invalid project id", "$.project.id"); text(project.name, issues, "$.project.name"); }
  for (const [name, value] of [["artifactSet", root.artifactSet], ["revision", root.revision]] as const) { const entry = shape(value, ["id", "name", "number"], name === "revision" ? ["id", "number"] : ["id", "name"], issues, `$.${name}`); if (entry) { text(entry.id, issues, `$.${name}.id`); if (name === "artifactSet") text(entry.name, issues, `$.${name}.name`); else if (!Number.isInteger(entry.number) || Number(entry.number) < 1) add(issues, "package.revision.number", "revision number must be positive", "$.revision.number"); } }
  if (!denseArray(root.sources, issues, "$.sources") || root.sources.length < 1 || root.sources.length > 50) add(issues, "package.sources", "sources must contain 1..50 items", "$.sources"); else root.sources.forEach((source, index) => { const entry = shape(source, ["specificationId", "snapshotSha256", "resources"], ["specificationId", "snapshotSha256", "resources"], issues, `$.sources[${index}]`); if (!entry) return; text(entry.specificationId, issues, `$.sources[${index}].specificationId`); hash(entry.snapshotSha256, issues, `$.sources[${index}].snapshotSha256`); if (!denseArray(entry.resources, issues, `$.sources[${index}].resources`) || entry.resources.length > 20) add(issues, "package.resources", "resources must be an array of at most 20 items", `$.sources[${index}].resources`); else entry.resources.forEach((resource, resourceIndex) => { const item = shape(resource, ["resourceId", "sha256"], ["resourceId", "sha256"], issues, `$.sources[${index}].resources[${resourceIndex}]`); if (item) { text(item.resourceId, issues, `$.sources[${index}].resources[${resourceIndex}].resourceId`); hash(item.sha256, issues, `$.sources[${index}].resources[${resourceIndex}].sha256`); } }); });
  const harness = shape(root.harness, ["version", "sha256"], ["version", "sha256"], issues, "$.harness"); if (harness) { text(harness.version, issues, "$.harness.version", 100); hash(harness.sha256, issues, "$.harness.sha256"); }
  const generation = shape(root.generation, ["workflow", "requestSha256", "adapter", "provider", "model", "attempts"], ["workflow", "requestSha256", "adapter", "provider", "model", "attempts"], issues, "$.generation"); if (generation) { if (generation.workflow !== "init") add(issues, "package.workflow", "workflow must be init", "$.generation.workflow"); hash(generation.requestSha256, issues, "$.generation.requestSha256"); text(generation.adapter, issues, "$.generation.adapter", 200); text(generation.provider, issues, "$.generation.provider", 120); text(generation.model, issues, "$.generation.model", 160); if (!Number.isInteger(generation.attempts) || Number(generation.attempts) < 1 || Number(generation.attempts) > 2) add(issues, "package.attempts", "attempts must be 1 or 2", "$.generation.attempts"); }
  if (!denseArray(root.contracts, issues, "$.contracts") || root.contracts.length < 3 || new Set(root.contracts).size !== root.contracts.length || root.contracts.some((item) => !["rb-headless-init/v1", "rb-manifest/v1", "rb-execution/v1", "rb-operational/v1"].includes(String(item)))) add(issues, "package.contracts", "contracts must be unique supported contracts", "$.contracts");
  if (!denseArray(root.validation, issues, "$.validation") || root.validation.length < 1) add(issues, "package.validation", "validation must be a non-empty array", "$.validation"); else { const names = new Set<string>(); root.validation.forEach((value, index) => { const entry = shape(value, ["name", "passed"], ["name", "passed"], issues, `$.validation[${index}]`); if (!entry) return; if (typeof entry.name !== "string" || !VALIDATIONS.has(entry.name)) add(issues, "package.validation.name", "Unknown validation name", `$.validation[${index}].name`); else if (names.has(entry.name)) add(issues, "package.validation.duplicate", "Validation names must be unique", `$.validation[${index}].name`); else names.add(entry.name); if (entry.passed !== true) add(issues, "package.validation.passed", "Published validation must pass", `$.validation[${index}].passed`); }); }
  if (!denseArray(root.files, issues, "$.files") || root.files.length < 1 || root.files.length > 2000) add(issues, "package.files", "files must contain 1..2000 items", "$.files"); else {
    const paths = new Set<string>(); let totalBytes = 0;
    root.files.forEach((value, index) => { const entry = shape(value, ["path", "bytes", "sha256", "mediaType"], ["path", "bytes", "sha256", "mediaType"], issues, `$.files[${index}]`); if (!entry) return; if (!isSafeRelativePath(entry.path)) add(issues, "package.path", "File path must be a safe normalized relative path", `$.files[${index}].path`); const collisionKey = normalizedRelativePathKey(entry.path); if (collisionKey !== undefined) { if (collisionKey === PACKAGE_MANIFEST_PATH_KEY) add(issues, "package.files.recursive", "Package manifest must not inventory itself", `$.files[${index}].path`); if (paths.has(collisionKey)) add(issues, "package.files.duplicate", "File paths must be unique after NFC/case normalization", `$.files[${index}].path`); else paths.add(collisionKey); } if (!Number.isInteger(entry.bytes) || Number(entry.bytes) < 0 || Number(entry.bytes) > 5242880) add(issues, "package.bytes", "File bytes must be in range", `$.files[${index}].bytes`); else totalBytes += Number(entry.bytes); hash(entry.sha256, issues, `$.files[${index}].sha256`); text(entry.mediaType, issues, `$.files[${index}].mediaType`); });
    if (totalBytes > 100 * 1024 * 1024) add(issues, "package.files.bytes.aggregate", "Package files may total at most 104857600 bytes", "$.files");
  }
  if (!isIsoDateTime(root.generatedAt)) add(issues, "package.generatedAt", "generatedAt must be an ISO date-time", "$.generatedAt");
  return { valid: issues.length === 0, issues, ...(issues.length === 0 ? { document: root } : {}) };
}

export function validateProjectPackageJson(source: string): ProjectPackageValidation { try { return validateProjectPackageValue(JSON.parse(source)); } catch (error) { return { valid: false, issues: [{ code: "package.json", message: error instanceof Error ? error.message : String(error), severity: "error", path: "$" }] }; } }
